name: Mirror sites

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'

jobs:
  mirror-kasparsdambis-lv:
    runs-on: ubuntu-20.04
    env:
      DEBUG: website-scraper:info
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install

      - name: Mirror kasparsdambis.lv
        run: |
          rm -rf docs/kasparsdambis.lv
          npm run mirror kasparsdambis.lv
      
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --force docs/kasparsdambis.lv
          git commit -m "Mirror on $(date)"
          git push --force origin main:gh-pages


