name: Mirror sites

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'

jobs:
  mirror-sites:
    name: Mirror sites
    runs-on: ubuntu-22.04
    env:
      DEBUG: website-scraper:info
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install dependencies
        run: npm install

      - name: Checkout existing mirrors
        run: |
          git checkout gh-pages -- docs

      - name: Mirror kasparsdambis.lv
        continue-on-error: true
        run: |
          git rm docs/kasparsdambis.lv
          npm run mirror kasparsdambis.lv
          git add docs/kasparsdambis.lv

      - name: Mirror kaspars.net
        continue-on-error: true
        run: |
          git rm docs/kaspars.net
          npm run mirror kaspars.net
          git add --force docs/kaspars.net
      
      - name: Commit changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m "Mirror on $(date)"
          git push --force origin main:gh-pages


